version: '3.8'

services:
  browserpilot:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"  # FastAPI
      - "5900:5900"  # VNC
      - "6080:6080"  # noVNC
    volumes:
      - ./results:/opt/results
      - ./logs:/opt/logs
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=True
      - VNC_PORT=5900
      - NOVNC_PORT=6080
      - VNC_PASSWORD=browserpilot
      - BROWSER_WIDTH=1280
      - BROWSER_HEIGHT=720
      - DEFAULT_MODEL=openai
      # Add your API keys here or use .env file
      # - OPENAI_API_KEY=your_openai_key
      # - ANTHROPIC_API_KEY=your_anthropic_key
      # - GEMINI_API_KEY=your_gemini_key
    restart: unless-stopped
    shm_size: 2gb  # Increase shared memory for browsers